project_id = "mpowpfgigzdpebtuohfk"

[functions.telegram-bot]
verify_jwt = false

[functions.telegram-diagnostic]
verify_jwt = false

[functions.notify-user-telegram]
verify_jwt = false

[functions.setup-debora-profile]
verify_jwt = false

[functions.analyze-image-with-waste-sorter]
verify_jwt = false

[functions.analyze-waste-image]
verify_jwt = false