// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpowpfgigzdpebtuohfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wb3dwZmdpZ3pkcGVidHVvaGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NzAxODksImV4cCI6MjA2NjU0NjE4OX0.gCeek4ItLGLpOhyybRL9JUTtATQFhccXd-84n-M29E8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);